DROP SEQUENCE TEST_COMPANY_ID;
CREATE SEQUENCE TEST_COMPANY_ID;

DROP TABLE TEST_COMPANY;
CREATE TABLE TEST_COMPANY (
		ID INTEGER NOT NULL PRIMARY KEY,
		NAME VARCHAR(128)
);

DROP SEQUENCE TEST_USER_ID;
CREATE SEQUENCE TEST_USER_ID;

DROP TABLE TEST_USER;
CREATE TABLE TEST_USER (
		ID INTEGER NOT NULL PRIMARY KEY,
		LOGIN VARCHAR(32),
		PASSWORD VARCHAR(32),
		SALARY DECIMAL(10,2),
		COMPANYID INTEGER
);


