DROP TABLE IF EXISTS TEST_COMPANY;
CREATE TABLE TEST_COMPANY (
		ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
		NAME VARCHAR(128)
);


DROP TABLE IF EXISTS TEST_USER;
CREATE TABLE TEST_USER (
		ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
		LOGIN VARCHAR(32),
		PASSWORD VARCHAR(32),
		SALARY DECIMAL(10,2),
		COMPANYID INTEGER
);

