DROP SEQUENCE TEST_COMPANY_ID;
CREATE SEQUENCE TEST_COMPANY_ID;

DROP TABLE TEST_COMPANY;
CREATE TABLE TEST_COMPANY (
		ID INTEGER NOT NULL PRIMARY KEY,
		NAME VARCHAR(128)
);

DROP SEQUENCE TEST_USER_ID;
CREATE SEQUENCE TEST_USER_ID;

DROP TABLE TEST_USER;
CREATE TABLE TEST_USER (
		ID INTEGER NOT NULL PRIMARY KEY,
		LOGIN VARCHAR(32),
		PASSWORD VARCHAR(32),
		SALARY DECIMAL(10,2),
		COMPANYID INTEGER
);

DROP SEQUENCE TEST_NUMBER_GENERATOR;
CREATE SEQUENCE TEST_NUMBER_GENERATOR;

DROP TABLE NumberGenerator;
CREATE TABLE NumberGenerator (
		id INTEGER NOT NULL PRIMARY KEY,
		year DECIMAL(4),
		departament VARCHAR(32),
		number DECIMAL(10)
);

